version: '3'
services:
  node:
    container_name: node
    build: .
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=a
      - MONGO_INITDB_ROOT_PASSWORD=a
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

volumes:
  mongo-db: